# Generated by Django 2.1.3 on 2018-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20181112_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
