# Generated by Django 2.1.3 on 2018-11-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_post_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='pub_date',
        ),
    ]
