# Generated by Django 2.1.3 on 2018-11-17 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0009_auto_20181117_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_title', models.TextField(max_length=30)),
                ('new_title', models.TextField(max_length=30)),
                ('old_content', models.TextField()),
                ('new_content', models.TextField()),
                ('edit_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edit_date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='edit_history',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.ArticleChanges'),
            preserve_default=False,
        ),
    ]
