# Generated by Django 2.1.3 on 2018-11-17 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0011_auto_20181117_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleChanges',
            new_name='ArticleChange',
        ),
    ]
